### ISSUE TITLE
Is this package going to be updated to null safety?

### ISSUE THREAD

**Issue by doughywilson** [google/charts#648] opened 2021-07-01 17:39 UTC
If so, any idea on timeline? I would really like to update my app to null safety but it depends on this package.

**Comment by yuriboeira11tx** [comment] 2021-07-01 17:40
Same problem.

**Comment by robhoefakker** [comment] 2021-07-01 19:02
The work is already done. There are more changes pushed so they want more validation before updating the package. 
If you want to try the current version you can use my fork. 
`charts_flutter:
    git:
      url: https://github.com/robhoefakker/charts.git
      path: charts_flutter`

When I use the main repo in my pubspec.yml I get a error due to the relative path of charts_common. 

`Running "flutter pub get" in agri24...                          
Error on line 18, column 11: Invalid description in the "charts_flutter" pubspec on the "charts_common" dependency: "../charts_common/" is a relative path, but this isn't a local pubspec.`

**Comment by doughywilson** [comment] 2021-07-01 19:16
> The work is already done. There are more changes pushed so they want more validation before updating the package.
> If you want to try the current version (null safety) you can use my fork.

That's great news. Glad to hear it's coming along. Thanks for the info.

**Comment by renancaraujo** [comment] 2021-07-02 00:30
This is a dupe of https://github.com/google/charts/issues/579#issuecomment-871749599

**Comment by deepak786** [comment] 2021-07-08 18:41
version `0.11.0` is released with null safety.

**Closed** 2021-07-19 11:20 UTC
