### ISSUE TITLE
Error message was reported after "flutter upgrade"

### ISSUE THREAD

**Issue by smallqs** [google/charts#666] opened 2021-08-11 06:16 UTC
../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/charts_flutter-0.11.0/lib/src/behaviors/legend/legend_entry_layout.dart:134:45: Error: The getter 'body1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../development/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body1'.
      color ??= Theme.of(context).textTheme.body1!.color;
                                            ^^^^^

**Comment by ImperialOctopus** [comment] 2021-08-12 19:00
Same problem here! I've got it working temporarily using a git dependency (of this repository) so I assume the problem's been fixed here but just not made it into a release yet. If you don't rely on things being stable that might get it working for now.

**Comment by SubigyaPanta** [comment] 2021-09-09 16:20
I'm getting this error after upgrading to Flutter 2.5. The issue seems to be already merged https://github.com/google/charts/pull/670 . When will this be released ?

**Comment by stuartmorgan** [comment] 2021-11-03 14:17
Duplicate of https://github.com/google/charts/issues/678

(While this issue is older, most of the discussion has ended up in that issue.)

**Closed by stuartmorgan** 2021-11-03 14:17 UTC
