### ISSUE TITLE
please do add support for null saftey.

### ISSUE THREAD

**Issue by Abin-Thankachan** [google/charts#628] opened 2021-05-04 08:59 UTC

**Comment by rahulrkhot** [comment] 2021-05-07 12:49
null safety required

**Comment by GitRubb** [comment] 2021-05-08 02:04
Anyway to run the app with null safety with the existing version of charts_flutter?

Also is this even in development anymore?

**Comment by Abin-Thankachan** [comment] 2021-05-08 06:55
> Anyway to run the app with null safety with the existing version of charts_flutter?
> 
> Also is this even in development anymore?

Yes you use // @dart=2.9  as the 1st line of the file that depends on this package without disabling null safety for other areas.

**Comment by johnpryan** [comment] 2021-05-17 23:07
This is a duplicate of https://github.com/google/charts/issues/579

**Comment by cbbraun** [comment] 2021-06-30 21:47
Duplicate of #579

**Closed** 2021-06-30 21:48 UTC
