### ISSUE TITLE
Can't compile the app

### ISSUE THREAD

**Issue by acx70** [google/charts#687] opened 2021-09-24 14:22 UTC
I get the following error when I compile my app:

../../../../flutter/.pub-cache/hosted/pub.dartlang.org/charts_flutter-0.11.0/lib/src/behaviors/legend/legend_entry_layout.dart:134:45: Error: The getter 'body1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body1'.

FAILURE: Build failed with an exception.

---------------------------------

charts_flutter: ^0.11.0

---------------------------------

flutter --version:
Flutter 2.5.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffb2ecea52 (7 days ago) • 2021-09-17 15:26:33 -0400
Engine • revision b3af521a05
Tools • Dart 2.14.2

**Comment by MiroslavPeterka1** [comment] 2021-09-26 04:47
Same

**Comment by RedsAnDev** [comment] 2021-09-27 20:39
same

**Comment by GlauberAlc** [comment] 2021-09-27 21:05
My solution:

dependencies:
  flutter:
    sdk: flutter
    charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter

**Comment by acx70** [comment] 2021-09-28 07:03
> 
> 
> My solution:
> 
> dependencies:
> flutter:
> sdk: flutter
> charts_flutter:
> git:
> url: git://github.com/google/charts.git
> path: charts_flutter

It works as temporary solution, but I think it should be fixed.
Note: you should add "publish_to: none" as follow:

`
publish_to: none

dependencies:
  flutter:
    sdk: flutter

charts_flutter: 
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
`

**Comment by hussamDana92** [comment] 2021-09-28 08:18
same

**Comment by amarildox** [comment] 2021-09-28 08:53
same problem

**Comment by ranthonissen** [comment] 2021-10-11 16:54
Duplicate of #685

**Comment by stuartmorgan** [comment] 2021-11-03 14:18
Closing as a duplicate of https://github.com/google/charts/issues/678

**Closed by stuartmorgan** 2021-11-03 14:18 UTC
